/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.views;

import javax.swing.JOptionPane;
import sistema.entidades.Funcionario;
import sistema.entidades.Pessoa;

/**
 *
 * @author MATHEUS-PC
 */
public class CadFuncionario extends javax.swing.JInternalFrame {

    Pessoa pessoa=null;
    Funcionario funcionario=null;
    
    public CadFuncionario() {
        initComponents();
    }
    
    public CadFuncionario(Funcionario funcionario){
        initComponents();
        this.funcionario=funcionario;
        
        edtCPF.setText(funcionario.getCdCpfCnpj());
        edtNome.setText(funcionario.getNmPessoa());
        edtTelefone.setText(funcionario.getTelefone());
        edtEndereco.setText(funcionario.getEndereco());
        btnPesq.setVisible(false);
        edtComissao.setText(String.valueOf(funcionario.getVlComissao()));
        edtHabilicao.setText(funcionario.getDocHabilitacao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtNome = new javax.swing.JTextField();
        btnPesq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtComissao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtHabilicao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de funcionários");

        edtNome.setEditable(false);

        btnPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/icons/lupa.png"))); // NOI18N
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("CPF/CNPJ");

        edtCPF.setEditable(false);

        jLabel3.setText("Endereço");

        edtEndereco.setEditable(false);

        jLabel4.setText("Telefone");

        edtTelefone.setEditable(false);

        jLabel5.setText("Vl. Comissão");

        jLabel6.setText("Doc Habilitação");

        edtHabilicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtHabilicaoActionPerformed(evt);
            }
        });

        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(edtTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 241, Short.MAX_VALUE))
                                    .addComponent(edtHabilicao, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(edtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtHabilicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        PesqPessoa pesq = new PesqPessoa(this);
        pesq.setTitle("Pesquisar pessoas");
        Principal.adicionarAoDsk(pesq);
        
        pesq.setVisible(true);
    }//GEN-LAST:event_btnPesqActionPerformed

    private void edtHabilicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtHabilicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtHabilicaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (pessoa!=null) {
            
            funcionario=new Funcionario(0,Double.parseDouble(edtComissao.getText()) , edtHabilicao.getText(), pessoa.getIdPessoa(), pessoa.getNmPessoa(), pessoa.getCdCpfCnpj(),pessoa.getDtnascimento(), pessoa.getTelefone(), pessoa.getEndereco());
            if(funcionario.inserir()){
                limpaCampos();
            }
        }else if(funcionario!=null){
            funcionario.setDocHabilitacao(edtHabilicao.getText());
            funcionario.setVlComissao(Double.parseDouble(edtComissao.getText()));
            if(funcionario.atualizar()){
                dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione a pessoa clicando na lupa");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    public void limpaCampos(){
        pessoa=null;
        funcionario=null;
        edtNome.setText("");
        edtTelefone.setText("");
        edtCPF.setText("");
        edtEndereco.setText("");
        edtHabilicao.setText("");
        edtComissao.setText("");
    }
    
    public void setPessoa(Pessoa pessoa){
        this.pessoa=pessoa;
        edtNome.setText(pessoa.getNmPessoa());
        edtTelefone.setText(pessoa.getTelefone());
        edtCPF.setText(pessoa.getCdCpfCnpj());
        edtEndereco.setText(pessoa.getEndereco());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesq;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtComissao;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtHabilicao;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
