/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistema.principal.Conexao;

/**
 *
 * @author MATHEUS-PC
 */
public class VisualizaComanda extends javax.swing.JInternalFrame {

    int idComanda;
    public VisualizaComanda(int id) {
        initComponents();
        idComanda=id;
        carregaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtCpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtTel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        edtAnimal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtCor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edtRaca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edtEspecie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        edtEntregador = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edtComissao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edtHabilitacao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dtSaida = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        vlServicos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        vlDescontos = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        vlTotal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServ = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        vlAcrescimos1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtCpf.setEditable(false);
        getContentPane().add(edtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 235, -1));

        jLabel1.setText("CPF/CNPJ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        edtTel.setEditable(false);
        getContentPane().add(edtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 220, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        edtEndereco.setEditable(false);
        getContentPane().add(edtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 590, -1));

        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Endereço");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        edtNome.setEditable(false);
        getContentPane().add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 590, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 700, 10));

        jLabel5.setText("ENTRAGADOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        edtAnimal.setEditable(false);
        getContentPane().add(edtAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 260, -1));

        jLabel6.setText("Nome:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        edtCor.setEditable(false);
        getContentPane().add(edtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 260, -1));

        jLabel7.setText("Cor:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        edtRaca.setEditable(false);
        getContentPane().add(edtRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 260, -1));

        jLabel8.setText("Raça:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        edtEspecie.setEditable(false);
        getContentPane().add(edtEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 260, -1));

        jLabel9.setText("Espécie:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 700, 10));

        jLabel10.setText("FINANCEIRO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        edtEntregador.setEditable(false);
        getContentPane().add(edtEntregador, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 260, -1));

        jLabel11.setText("Nome:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        edtComissao.setEditable(false);
        getContentPane().add(edtComissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 260, -1));

        jLabel12.setText("Comissão");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        edtHabilitacao.setEditable(false);
        getContentPane().add(edtHabilitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 260, -1));

        jLabel13.setText("Habilitação");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 80, -1));

        dtSaida.setEditable(false);
        getContentPane().add(dtSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 260, -1));

        jLabel14.setText("dt de Saída");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 690, 10));

        jLabel15.setText("ANIMAL");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel16.setText("CLIENTE");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        vlServicos.setEditable(false);
        getContentPane().add(vlServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 90, -1));

        jLabel17.setText("Serviços:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        vlDescontos.setEditable(false);
        getContentPane().add(vlDescontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 100, -1));

        jLabel18.setText("Descontos");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, -1));

        vlTotal.setEditable(false);
        getContentPane().add(vlTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 90, -1));

        jLabel19.setText("TOTAL");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        txtServ.setEditable(false);
        txtServ.setColumns(20);
        txtServ.setRows(5);
        jScrollPane1.setViewportView(txtServ);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 650, 70));

        jLabel20.setText("Vl serviços");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        vlAcrescimos1.setEditable(false);
        getContentPane().add(vlAcrescimos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 90, -1));

        jLabel21.setText("Acresc.");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dtSaida;
    private javax.swing.JTextField edtAnimal;
    private javax.swing.JTextField edtComissao;
    private javax.swing.JTextField edtCor;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtEntregador;
    private javax.swing.JTextField edtEspecie;
    private javax.swing.JTextField edtHabilitacao;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtRaca;
    private javax.swing.JTextField edtTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea txtServ;
    private javax.swing.JTextField vlAcrescimos1;
    private javax.swing.JTextField vlDescontos;
    private javax.swing.JTextField vlServicos;
    private javax.swing.JTextField vlTotal;
    // End of variables declaration//GEN-END:variables

    private void carregaCampos() {
        // conexão
        Connection conexao;
        // instrucao SQL
        Statement instrucaoSQL;
        // resultados
        ResultSet resultados;
        
        try {
            // conectando ao banco de dados
            conexao = DriverManager.getConnection(Conexao.servidor, Conexao.usuario, Conexao.senha);

            // criando a instrução SQL
            instrucaoSQL = conexao.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sql="select top(1) * from vwComandas where idComanda="+idComanda;
            
            resultados = instrucaoSQL.executeQuery(sql);

           

            while (resultados.next()) {
                edtNome.setText(resultados.getString("nmCliente"));
                edtCpf.setText(resultados.getString("cpfCliente"));
                edtEndereco.setText(resultados.getString("endCliente"));
                edtTel.setText(resultados.getString("telCliente"));
                
                edtAnimal.setText(resultados.getString("NmAnimal"));
                edtCor.setText(resultados.getString("cor"));
                edtRaca.setText(resultados.getString("raca"));
                edtEspecie.setText(resultados.getString("especie"));
                
                edtEntregador.setText(resultados.getString("nmFunc"));
                edtComissao.setText(String.valueOf(resultados.getDouble("vlComissao")));
                edtHabilitacao.setText(resultados.getString("docHabilitacao"));
                dtSaida.setText(resultados.getString("dtConcluido"));
                
                 
                vlAcrescimos1.setText(resultados.getString("acrescimos"));
                vlDescontos.setText(resultados.getString("desconto"));
                vlServicos.setText(resultados.getString("vlServ"));
                
                txtServ.setText(resultados.getString("servicos"));
                double d=resultados.getDouble("vlServ")+resultados.getDouble("acrescimos")+resultados.getDouble("desconto");
                vlTotal.setText(String.valueOf(d));
            }

            conexao.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao carregar dados.");
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
